modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "frogboimobs"
version = "${version}"
displayName = "FrogboiMobs"
authors = "Vercte"
description = '''

'''
#logoFile = ""

[[dependencies.frogboimobs]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.frogboimobs]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"


